name: "Frontend Deployment"

on:
  push:
    branches:
      - main # Or your default branch
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'

permissions:
  contents: read

jobs:
  deploy:
    name: "Deploy Frontend to S3 and Invalidate CloudFront"
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: "us-east-1"
      # Get S3 bucket name and CloudFront ID from Terraform outputs or define here
      # Option 1: Define statically (replace after first TF apply)
      # S3_BUCKET_NAME: "grocery-assistant-frontend-prod-xxxx" 
      # CLOUDFRONT_ID: "E1234567890ABC"
      # Option 2: Use Terraform output (requires reading state or passing outputs)
      # This example assumes static names/secrets for simplicity

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false # Ensure direct terraform commands are used

      - name: Terraform Init for Output Reading
        id: init
        run: |
          # Ensure terraform directory exists
          if [ ! -d "terraform" ]; then
            echo "Error: Terraform directory not found. Make sure the code is checked out correctly."
            exit 1
          fi
          
          echo "Initializing Terraform to read state from S3 backend..."
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=prod/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_DEFAULT_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_STATE_LOCK_TABLE }}" \
            -reconfigure
        working-directory: ./terraform
        env:
          # Prevent Terraform from trying to prompt for input
          TF_INPUT: false

      - name: Get API Gateway Invoke URL from Terraform Output
        id: get_api_url
        run: |
          echo "Reading api_gateway_invoke_url from Terraform state..."
          API_URL=$(terraform output -raw api_gateway_invoke_url)
          if [ -z "$API_URL" ]; then
            echo "Error: Failed to retrieve api_gateway_invoke_url from Terraform output."
            exit 1
          fi
          echo "API_URL=${API_URL}" >> $GITHUB_ENV
          echo "Successfully retrieved API Gateway URL."
        working-directory: ./terraform
        env:
          TF_INPUT: false

      - name: Update Frontend Config with API URL
        run: |
          CONFIG_FILE="frontend/js/config.js"
          PLACEHOLDER_LINE_START="const API_GATEWAY_INVOKE_URL =" # Identify the line start
          
          if [ ! -f "$CONFIG_FILE" ]; then
            echo "Error: Frontend config file not found at $CONFIG_FILE"
            exit 1
          fi
          
          if [ -z "${{ env.API_URL }}" ]; then
            echo "Error: API_URL environment variable is not set. Cannot update config."
            exit 1
          fi

          echo "Updating $CONFIG_FILE with API URL: ${{ env.API_URL }}"
          # Use sed to replace the entire line starting with PLACEHOLDER_LINE_START
          # Using '|' as delimiter for sed to handle '/' in the URL
          # Escape potential special characters in the URL for sed
          ESCAPED_API_URL=$(printf '%s\n' "${{ env.API_URL }}" | sed 's:[][\\/.^$*]:\\&:g')
          sed -i "s|^${PLACEHOLDER_LINE_START}.*;|${PLACEHOLDER_LINE_START} '${ESCAPED_API_URL}';|" $CONFIG_FILE

          echo "Verifying replacement in $CONFIG_FILE:"
          grep "${PLACEHOLDER_LINE_START}" $CONFIG_FILE || (echo "Verification failed: Line not found after replacement." && exit 1)
          echo "Frontend config updated successfully."

      # Optional: Add build step if needed (e.g., npm run build)
      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18' # Or your required version
      # - name: Install Dependencies
      #   run: npm ci
      #   working-directory: ./frontend
      # - name: Build Frontend
      #   run: npm run build # Adjust build command if necessary
      #   working-directory: ./frontend

      - name: Deploy to S3
        run: |
          echo "Deploying frontend to S3..."
          # Replace with actual bucket name after first Terraform apply
          S3_BUCKET_NAME=$(aws s3api list-buckets --query 'Buckets[?starts_with(Name, `groceryassistant-frontend-prod-`)].Name' --output text | head -n 1)
          
          if [ -z "$S3_BUCKET_NAME" ]; then echo "S3 bucket name not found!"; exit 1; fi

          echo "Syncing files to bucket: $S3_BUCKET_NAME"
          # Sync contents of frontend directory (or build output dir if using build step)
          # Exclude unnecessary files
          aws s3 sync frontend/ s3://${S3_BUCKET_NAME} --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "node_modules/*" \
            --exclude "*.sh" \
            --exclude "*.js.map" \
            --exclude "run-local.js" \
            --exclude "deploy.js" \
            --exclude "deploy-config.json" \
            --exclude "s3-cors-config.json" \
            --exclude ".htaccess" \
            --exclude "web.config" \
            --exclude "README.md" 
          echo "S3 sync complete."

      - name: Invalidate CloudFront Cache
        run: |
          echo "Invalidating CloudFront cache..."
          # Replace with actual CloudFront Distribution ID from secrets or TF output
          CLOUDFRONT_ID=${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} 
          
          if [ -z "$CLOUDFRONT_ID" ]; then 
            echo "CLOUDFRONT_DISTRIBUTION_ID secret not set. Attempting to find distribution..."
            # Attempt to find distribution ID based on tags or comment (less reliable)
            CLOUDFRONT_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Comment=='CloudFront distribution for GroceryAssistant frontend'].Id" --output text)
            if [ -z "$CLOUDFRONT_ID" ]; then 
              echo "Could not automatically find CloudFront Distribution ID. Please set the CLOUDFRONT_DISTRIBUTION_ID secret."; 
              exit 1; 
            fi
            echo "Found CloudFront ID: $CLOUDFRONT_ID"
          fi

          aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_ID" --paths "/*"
          echo "CloudFront invalidation created."
